Repository python-discord/branding, pull requests merged in 2020-11, with the labels that each got.

#103 Fix okhandbutflipped emoji
  emotes/other/dist/okhandbutflipped.png
  emotes/other/src/okhandbutflipped.svg
Labels: area: icons

#105 Add red cross icon
  icons/checkmark/red-cross-dist.png
  icons/checkmark/red-cross-src.svg
Labels: area: icons, type: feature

#61 More lemojis, always more lemojis
  emotes/lemoji/dist/lemon_raised_eyebrow.png
  emotes/lemoji/dist/lemon_tongue.png
  emotes/lemoji/src/lemon_raised_eyebrow.svg
  emotes/lemoji/src/lemon_tongue.svg
Labels: area: lemojis
