Repository python-discord/branding, pull requests merged in 2020-09, with the labels that each got.

#62 Add ducky lemon
  emotes/duckies/duckylemon.svg
Labels: needs 2 approvals

#64 Beard structure lemojis
  emotes/lemoji/dist/lemon_beard_structure/blank.png
  emotes/lemoji/dist/lemon_beard_structure/end_b.png
  emotes/lemoji/dist/lemon_beard_structure/end_l.png
  emotes/lemoji/dist/lemon_beard_structure/end_r.png
  emotes/lemoji/dist/lemon_beard_structure/end_t.png
  emotes/lemoji/dist/lemon_beard_structure/head_b.png
  emotes/lemoji/dist/lemon_beard_structure/head_l.png
  emotes/lemoji/dist/lemon_beard_structure/head_r.png
  emotes/lemoji/dist/lemon_beard_structure/head_t.png
  emotes/lemoji/dist/lemon_beard_structure/l-r.png
  emotes/lemoji/dist/lemon_beard_structure/l_b.png
  emotes/lemoji/dist/lemon_beard_structure/l_r_b.png
  emotes/lemoji/dist/lemon_beard_structure/l_t.png
  emotes/lemoji/dist/lemon_beard_structure/l_t_b.png
  emotes/lemoji/dist/lemon_beard_structure/l_t_r.png
  emotes/lemoji/dist/lemon_beard_structure/l_t_r_b.png
  emotes/lemoji/dist/lemon_beard_structure/r_b.png
  emotes/lemoji/dist/lemon_beard_structure/t_b.png
  emotes/lemoji/dist/lemon_beard_structure/t_r.png
  emotes/lemoji/dist/lemon_beard_structure/t_r_b.png
  emotes/lemoji/src/lemon_beard_structure/blank.svg
  emotes/lemoji/src/lemon_beard_structure/end_b.svg
  emotes/lemoji/src/lemon_beard_structure/end_l.svg
  emotes/lemoji/src/lemon_beard_structure/end_r.svg
  emotes/lemoji/src/lemon_beard_structure/end_t.svg
  emotes/lemoji/src/lemon_beard_structure/head_b.svg
  emotes/lemoji/src/lemon_beard_structure/head_l.svg
  emotes/lemoji/src/lemon_beard_structure/head_r.svg
  emotes/lemoji/src/lemon_beard_structure/head_t.svg
  emotes/lemoji/src/lemon_beard_structure/l_b.svg
  emotes/lemoji/src/lemon_beard_structure/l_r.svg
  emotes/lemoji/src/lemon_beard_structure/l_r_b.svg
  emotes/lemoji/src/lemon_beard_structure/l_t.svg
  emotes/lemoji/src/lemon_beard_structure/l_t_b.svg
  emotes/lemoji/src/lemon_beard_structure/l_t_r.svg
  emotes/lemoji/src/lemon_beard_structure/l_t_r_b.svg
  emotes/lemoji/src/lemon_beard_structure/r_b.svg
  emotes/lemoji/src/lemon_beard_structure/t_b.svg
  emotes/lemoji/src/lemon_beard_structure/t_r.svg
  emotes/lemoji/src/lemon_beard_structure/t_r_b.svg
Labels: needs 2 approvals

#65 lemon_ping and lemon_grimace emoji additions
  emotes/lemoji/dist/lemon_grimace.png
  emotes/lemoji/dist/lemon_ping.png
  emotes/lemoji/src/lemon_grimace.svg
  emotes/lemoji/src/lemon_ping.svg
Labels: needs 2 approvals

#67 Updated lemoji template
  emotes/lemoji/src/lemon_template_straightened.svg
  emotes/lemoji/src/lemon_template_tilted.svg
  emotes/lemoji/src/template/RAW.svg
  emotes/lemoji/src/template/tilted.svg
  emotes/lemoji/src/template/upright.svg
Labels: needs 2 approvals

#69 Recreated dice emojis
  emotes/dice/distro/1.png
  emotes/dice/distro/2.png
  emotes/dice/distro/3.png
  emotes/dice/distro/4.png
  emotes/dice/distro/5.png
  emotes/dice/distro/6.png
  emotes/dice/src/1.svg
  emotes/dice/src/2.svg
  emotes/dice/src/3.svg
  emotes/dice/src/4.svg
  emotes/dice/src/5.svg
  emotes/dice/src/6.svg
Labels: needs 2 approvals

#70 Fix typo in filename
  emotes/tilesets/lemoji_beard/dist/lrb.png
Labels: needs 2 approvals

#72 add `duckybear` emoji
  emotes/duckies/duckybear.png
Labels: needs 2 approvals

#71 Fix typo in directory name
  emotes/tilesets/pydis_snake/dist/blank.png
  emotes/tilesets/pydis_snake/dist/center.png
  emotes/tilesets/pydis_snake/dist/eb.png
  emotes/tilesets/pydis_snake/dist/el.png
  emotes/tilesets/pydis_snake/dist/er.png
  emotes/tilesets/pydis_snake/dist/et.png
  emotes/tilesets/pydis_snake/dist/hb.png
  emotes/tilesets/pydis_snake/dist/hl.png
  emotes/tilesets/pydis_snake/dist/hr.png
  emotes/tilesets/pydis_snake/dist/ht.png
  emotes/tilesets/pydis_snake/dist/lb.png
  emotes/tilesets/pydis_snake/dist/lr.png
  emotes/tilesets/pydis_snake/dist/lrb.png
  emotes/tilesets/pydis_snake/dist/lt.png
  emotes/tilesets/pydis_snake/dist/ltb.png
  emotes/tilesets/pydis_snake/dist/ltr.png
  emotes/tilesets/pydis_snake/dist/rb.png
  emotes/tilesets/pydis_snake/dist/tb.png
  emotes/tilesets/pydis_snake/dist/tr.png
  emotes/tilesets/pydis_snake/dist/trb.png
Labels: needs 1 approval

#73 Add empty and full dice
  emotes/dice/distro/0.png
  emotes/dice/distro/9.png
  emotes/dice/src/0.svg
  emotes/dice/src/9.svg
Labels: enhancement
