Repository python-discord/branding, pull requests merged in 2021-03, with the labels that each got.

#124 Add banner pattern tiles
  logos/banner_pattern/banner_pattern.png
  logos/banner_pattern/banner_pattern.svg
Labels: area: pydis, priority: high, type: feature

#125 Fix artifact in banner pattern png
  logos/banner_pattern/banner_pattern.png
Labels: area: pydis, type: enhancement

#115 Add lemon_starstruck lemoji
  emotes/lemoji/dist/lemon_starstruck.png
  emotes/lemoji/src/lemon_starstruck.svg
Labels: area: lemojis

#110 Add :lemon_angrysad:
  emotes/lemoji/dist/lemon_angrysad.png
  emotes/lemoji/src/lemon_angrysad.svg
Labels: area: lemojis

#96 Adding Diwali assets
  README.md
  seasonal/diwali/assets/diwali.min.svg
  seasonal/diwali/assets/diwali.png
  seasonal/diwali/assets/diwali.svg
  seasonal/diwali/assets/diwali_256.png
  seasonal/diwali/assets/diwali_512.png
  seasonal/diwali/assets/diwali_64.png
  seasonal/diwali/assets/diwali_large.png
  seasonal/diwali/assets/diwali_transparent.png
  seasonal/diwali/avatar.png
  seasonal/diwali/banner.png
  seasonal/diwali/server_icons/diwali_256.png
Labels: needs 1 approval

#112 Fix valentines banner colour
  seasonal/valentines/banner.png
Labels: area: pydis

#94 Add a `:ducky_bike:` emoji
  emotes/duckies/duckybike.svg
Labels: area: icons, status: awaiting response
